name: CI Belly

on:
  push:
    branches: [main]
    paths:
      - 'Actividades/Actividad7/**'
  pull_request:
    branches: [main]
    paths:
      - 'Actividades/Actividad7/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest behave flake8
          pip install -r Actividades/Actividad7/requirements.txt || true

      - name: Verificar formato de codigo con flake8
        run: |
          echo "Verificando calidad del codigo con flake8..."
          flake8 Actividades/Actividad7/src/ Actividades/Actividad7/test/ Actividades/Actividad7/features/steps/ --max-line-length=100

  tests_unitarios:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Ejecutar pruebas unitarias con pytest
        run: |
          echo "Ejecutando pruebas unitarias..."
          pytest Actividades/Actividad7/test/

  tests_bdd:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave

      - name: Ejecutar pruebas BDD
        run: |
          echo "Ejecutando pruebas BDD con behave..."
          behave Actividades/Actividad7/features/ --no-capture --no-capture-stderr
